### ISSUE TITLE
Create a unique logo with some "Svelte" element to it

### ISSUE THREAD

**Issue by CaptainCodeman** [CaptainCodeman/svelte-headlessui#1]

**Comment by hshoob** [comment]
I made this logo; let me know if you like it. 


![svelteheadlessui_logo](https://user-images.githubusercontent.com/18516326/209447984-d836e471-25ee-4711-9350-4fbfc8543777.png)

**Comment by CaptainCodeman** [comment]
Like it? I love it! That's awesome ... I'm gonna have to rethink my whole "disbelief in Santa" thing now LOL

Should I just use a crop from those images or do you have an SVG version? Or feel free to create a PR to add it but either way please include any link to any profile or portfolio site I can add as part of crediting you.

And many thanks for doing this!

**Comment by hshoob** [comment]
Glad you like it. Created a PR for the SVGs, and added the favicon. I was thinking of polishing the UI for docs too, but that's in Astro.

**Comment by CaptainCodeman** [comment]
Yeah, there were no great SvelteKit docs systems that I could find and the docs are very incomplete right now. I was thinking of maybe one day converting the [TailwindUI Protocol ](https://tailwindui.com/templates/protocol),which looks slick, to Svelte.

**Comment by CaptainCodeman** [comment]
Thanks for the PR - I updated the docs and readme to use them.

Looks great, thanks again!
