### ISSUE TITLE
Ability to add something other than button behavior in the "menu"?

### ISSUE THREAD

**Issue by saturnonearth** [CaptainCodeman/svelte-headlessui#10]
I want to change the menu dropdown buttons to trigger a form, and another to be an anchor link, but the current implementation does not allow it. It seems to disable any events on that actual menu item in order to file the custom event.

**Comment by CaptainCodeman** [comment]
Can you post a code snippet of what you mean? I tried adding an `on:click` handler directly to the buttons [here](https://github.com/CaptainCodeman/svelte-headlessui/blob/master/packages/lib/src/routes/menu/%2Bpage.svelte#L60) and that seems to work, so I'm probably not fully understanding what you're describing.

**Comment by saturnonearth** [comment]
`          
                    <a use:menu.item class="w-full flex items-center" href={option.href(id)}>
                    <Icon src={option.icon} theme="outline" width="20" height="20" class="flex-shrink-0 mr-2 h-5 w-5" />{option.text}</a>
`
![Snap](https://user-images.githubusercontent.com/12503538/207417714-67f44214-a5ba-496c-a15e-474998edcee5.png)

**Comment by CaptainCodeman** [comment]
Ah, I see - I probably just need to remove the `.preventDefault()` that get's added. I'll check that doesn't affect anything, I don't think it would. It should then also allow you to use the different menu options as different form submit actions.

**Comment by saturnonearth** [comment]
Sadly it appears to still be blocked somehow.

**Comment by CaptainCodeman** [comment]
Sorry, I haven't had chance to publish it yet :)

**Comment by saturnonearth** [comment]
haha oops 🤦

**Comment by CaptainCodeman** [comment]
No worries, should be there now.
