### ISSUE TITLE
Weird behavior when clicking Menu

### ISSUE THREAD

**Issue by saturnonearth** [CaptainCodeman/svelte-headlessui#11]
When clicking "Menu" you can get some weird behavior such the menu re-opening. To reproduce it you can click an item, and then quickly move the mouse up to the next item. This will cause it to re-open.

[https://i.imgur.com/eqevgt6.gif](https://i.imgur.com/eqevgt6.gif)

**Comment by CaptainCodeman** [comment]
Thanks for the example - I can see what it's doing
