### ISSUE TITLE
Do not require function onSelect for Menu

### ISSUE THREAD

**Issue by saturnonearth** [CaptainCodeman/svelte-headlessui#13]
If we are just using anchor links or forms and we don't need to track the events in JS, we should not need to have `function onSelect(e: Event)`. As of now, if you omit this function, it will cause an error.

`ReferenceError: onSelect is not defined`

**Comment by CaptainCodeman** [comment]
That should just be in the consumer, sounds like you may still have `on:select={onSelect}` on the menu button (?)

**Comment by saturnonearth** [comment]
You're correct! My bad.
