### ISSUE TITLE
Test functionalities across browsers

### ISSUE THREAD

**Issue by oganexon** [CaptainCodeman/svelte-headlessui#19]
Hi there, really love the project

Some components don't properly work on the latest version of Firefox, like Combobox or Listbox (the list appears but nothing is mouse clickable)
Although everything works if I use keyboard navigation :)

Keep up the good work !

**Comment by CaptainCodeman** [comment]
Thanks for the heads-up, I'll test it out and see if I can fix it.

**Comment by CaptainCodeman** [comment]
Hopefully that fixes it - looks like setting role property wasn't reflected to an attribute (and those were used to determine mouseover behaviour).

**Comment by oganexon** [comment]
Awesome, it works now on Firefox !

I tested on some other environments, and it seems broken on mobile too... (touch input)

**Comment by CaptainCodeman** [comment]
Thanks for confirming.

I have touch to look at as #6

**Comment by CaptainCodeman** [comment]
OK, that should be fixed with #20
