### ISSUE TITLE
onSelect not getting fired for Combobox

### ISSUE THREAD

**Issue by rohanrajpal** [CaptainCodeman/svelte-headlessui#25]
In the following docs for combobox

https://captaincodeman.github.io/svelte-headlessui/combobox/

If you select any element from the list, it does not call the `onSelect` method. This can be verified by just opening the console & no log is printed when an item is selected. If you open the docs for listbox on the other hand, the console log works as expected. Also verified by using the library myself & the `onSelect` is not gettting fired.

Additionally, I I search for something that is not in the list, the following error shows up

<img width="601" alt="image" src="https://user-images.githubusercontent.com/7023147/211159847-c9123bc6-1270-4759-bb8d-4bce61d416a9.png">

Let me know if I can help in fixing this issues, once again, thanks for the effort!

**Comment by CaptainCodeman** [comment]
Thanks for the catch!

I think the example code was wrong with the event listener added to the outer button (which isn't actually used as a button)

**Comment by rohanrajpal** [comment]
> Thanks for the catch!
> 
> I think the example code was wrong with the event listener added to the outer button (which isn't actually used as a button)

You're welcome! Also shall I create a new issue for the error that comes up when you search for something that is not in the list?

Example: Try typing "fasfa" in the combobox example & notice the error in the console.

**Comment by CaptainCodeman** [comment]
Yes please, I just realized it didn't fix that too (I wasn't pressing enter after)

**Comment by CaptainCodeman** [comment]
Actually, it's pretty quick - I'll just tack it on to this issue

**Comment by CaptainCodeman** [comment]
Hopefully that sorts it, thanks again for the issue :)
