### ISSUE TITLE
How to make a dialog non-closable?

### ISSUE THREAD

**Issue by marchellodev** [CaptainCodeman/svelte-headlessui#30]
Hello, how do I make it so that the opened dialog can only be closed with me manually evoking `dialog.close()`? The library's dialog component uses only the `Transition` component (not `Dialog` like in the official headlessui implementation) so I have no idea how to do this.

**Comment by CaptainCodeman** [comment]
I don't think that's _really_ a dialog though, more of a splash / progress display. Even if it might happen to be styled in a similar way, a proper dialog used for input / action should always be cancellable.

If using something means disabling and removing all the features of that thing, it's possibly a sign that it's being mis-used.
