### ISSUE TITLE
Consider adding a prominent link to the github repo on the website

### ISSUE THREAD

**Issue by ul8** [CaptainCodeman/svelte-headlessui#37]
...as that will lead to more people starring it, and stars drive adoption.

Thanks so much for the excellent work on this by the way!

**Comment by CaptainCodeman** [comment]
Yeah, I have a few components that don't have links to github and npm on the demo pages!

**Comment by mattcroat** [comment]
I opened a pull request #38 to address this.

**Comment by CaptainCodeman** [comment]
Thanks, just merged it 👍🏻
