### ISSUE TITLE
Add project setup instructions in the readme

### ISSUE THREAD

**Issue by mattcroat** [CaptainCodeman/svelte-headlessui#39]
I'm not that familiar with monorepos but I managed to get the project working using intuition and some luck but it would be great to include instructions for people who want to contribute and ones that just want to explore and learn how it works — I can open a pull request if someone enlightens me on the correct setup.

**Comment by CaptainCodeman** [comment]
I don't think every library should have instructions on how to use the tools, but we should have some high level description about what is where and which tools are used.

In this case it's "use pnpm and run the `dev` script in the lib project"

**Comment by mattcroat** [comment]
> we should have some high level description about what is where and which tools are used

That's what I meant! 😄

> In this case it's "use pnpm and run the dev script in the lib project"

Do you run install for the dependencies from the root or have to do it inside `lib` and `docs` for each package? I hoped to find the answer in pnpm docs but the workspace section is short.

**Comment by CaptainCodeman** [comment]
`pnpm i` from the root installs all dependencies. `pnpm -r build` from the root builds everything.

A google search will pull up plenty of resources on how mono repos work and specifically how to use pnpm.
