### ISSUE TITLE
Docs: typos

### ISSUE THREAD

**Issue by Greenheart** [CaptainCodeman/svelte-headlessui#47]
Thanks for creating this!

There's a consistent typo in multiple files of this repo: `WIA-ARIA` should be `WAI-ARIA`.

https://github.com/search?q=repo%3ACaptainCodeman%2Fsvelte-headlessui%20WIA&type=code

For reference, see https://developer.mozilla.org/en-US/docs/Learn/Accessibility/WAI-ARIA_basics

**Comment by CaptainCodeman** [comment]
I would have _sworn_ it stood for Web Internal Accessibility!
