### ISSUE TITLE
Feature request: multiple select for listbox and combobox

### ISSUE THREAD

**Issue by zerosym** [CaptainCodeman/svelte-headlessui#49]
Apologies if I've missed something, but after a look through the code I couldn't determine an easy way of hacking together a solution for multiple select.  Primarily I think the issue is needing alternate behavior for `use:listbox.items` for it to stay open after a selection.

It was implemented in the canonical version a while back:
https://github.com/tailwindlabs/headlessui/pull/1243

Also, there's a slight difference in behavior with selects and menus -- when triggering mouse down on an item and then releasing outside the menu it should remain open.

**Comment by leerobert** [comment]
Along with multiple select, an empty input combobox would be nice (allowing placeholder). Headless ui has this via `null`

**Comment by thanhtschoepe** [comment]
I second this request. @CaptainCodeman Thank you so much for the port btw!
