### ISSUE TITLE
What is Selctor.svelte, Check.slte in ListBox example?

### ISSUE THREAD

**Issue by ethanfox** [CaptainCodeman/svelte-headlessui#51]
What are these files? What is their purpose? Why are they not included?

**Comment by CaptainCodeman** [comment]
They are just SVG icons wrapped as Svelte components. e.g.:

```html
<svg class={$$props.class} fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2" aria-hidden="true">
	<path stroke-linecap="round" stroke-linejoin="round" d="M8 9l4-4 4 4m0 6l-4 4-4-4" />
</svg>
```

https://github.com/CaptainCodeman/svelte-headlessui/blob/master/packages/lib/src/routes/listbox/Selector.svelte

**Comment by padrepitufo** [comment]
Had the same question, thank you for posting.  I wonder if many people try out those components and just give up when it doesn't work.

That link no longer works btw, but thank you for the basic explanation @CaptainCodeman

**Comment by CaptainCodeman** [comment]
That was when it was in a mono repo, the link now is:
