### ISSUE TITLE
Safari: Modal breaks when clicking outside of modal to close

### ISSUE THREAD

**Issue by CyberDie22** [CaptainCodeman/svelte-headlessui#53]
After you click outside the modal to close it, the modal no longer appears (the full screen background does, just not the modal) and you cannot close it anymore

Broken in Safari 16.3
This works fine in Firefox 111, Chrome 112, and Edge 111.

Code: The example code for the modal on the docs.

**Comment by CyberDie22** [comment]
Link to repo with code that doesn't work:
https://github.com/CyberDie22/svelte-headlessui-temp

**Comment by CaptainCodeman** [comment]
I think this is fixed, feel free to re-open if not.
