### ISSUE TITLE
Bug: Combobox trapping focus

### ISSUE THREAD

**Issue by junwen-k** [CaptainCodeman/svelte-headlessui#58]
Hi, thank you for porting this Headless UI library for Svelte.

Seems like Combobox is currently trapping focus, you can reproduce the issue by trying to `tab` it out from Combobox. Here is a video demo on the issue:

https://github.com/CaptainCodeman/svelte-headlessui/assets/40173716/6e4b049d-bb70-478f-a8d8-5e3890789622

As you can see, the original React version works as expected.

Your Svelte version:

https://captaincodeman.github.io/svelte-headlessui/combobox/

Original React version:

https://headlessui.com/react/combobox

Thank you.

**Comment by CaptainCodeman** [comment]
I still have a bit more testing to do to check everything is working, but if you want to try out the changes they are on this branch:
https://github.com/CaptainCodeman/svelte-headlessui/tree/keys
