### ISSUE TITLE
Bug: Dragging (selecting text) from inside dialog to outside of dialog causes dialog to close

### ISSUE THREAD

**Issue by leerobert** [CaptainCodeman/svelte-headlessui#59]
Expected behavior: dragging inside of a dialog and having the drag selection end outside of the dialog should not cause the dialog to close.

**Comment by CaptainCodeman** [comment]
Can you explain it a bit more and / or post a reproduction [e.g. stackblitz](https://stackblitz.com/edit/svelte-kit)

The original post mentioned a click handler outside of the dialog (?)

**Comment by leerobert** [comment]
Hi @CaptainCodeman 

Here's a simple video reproducing the issue:

https://www.loom.com/share/3f20275cb0194a448e868fdfdc502016

**Comment by leerobert** [comment]
Nice work @CaptainCodeman 👍🏼
