### ISSUE TITLE
Tab Components

### ISSUE THREAD

**Issue by davemaul** [CaptainCodeman/svelte-headlessui#63]
Hi @CaptainCodeman,

props to this super nice and easy to style library. I just wanted to ask the question when the see apparently already implemented Tabs component will be released. Are there any todos one you need help with? Asking because the original library has a rather unpleasant approach to styling.

Thanks!

**Comment by CaptainCodeman** [comment]
Yeah, I need to check where I got up to with that one and try to dedicate some time to getting it completed.

**Comment by davemaul** [comment]
That'd be great! Let me know if you need some support. :)

**Comment by CaptainCodeman** [comment]
I added an initial version of the Tabs component, it's not published to npm yet but you can [try it out](https://captaincodeman.github.io/svelte-headlessui/tabs/)

The `createTabs` factory accepts an `auto` property that defaults to `true`, setting it to false makes tab activation manual (using the arrow keys). There's also an `orientation` option that can be set to `horizontal` (default) or `vertical`.

Let me know what you think.
