### ISSUE TITLE
Unable to select the previously selected menu

### ISSUE THREAD

**Issue by eXodes** [CaptainCodeman/svelte-headlessui#83]
**Describe the bug**
Selected the same menu twice doesn't trigger the `on:select` event for `menu.button`.

**To Reproduce**
Setup based on the example in docs: https://captaincodeman.github.io/svelte-headlessui/menu

**Expected behavior**
Selecting the menu should trigger the `on:select` event.

**Screenshots**
![2023-12-27 21 35 13](https://github.com/CaptainCodeman/svelte-headlessui/assets/9076458/e7b85dba-e776-4bf4-a79c-f14b13364791)

**Comment by CaptainCodeman** [comment]
Thanks, I'll look into it
