### ISSUE TITLE
Prevent close and onClose event?

### ISSUE THREAD

**Issue by hernandp-nimble** [CaptainCodeman/svelte-headlessui#85]
It a lot of use cases we want to add functionality when closing as prevent the close whenever a condition is met.

**Comment by CaptainCodeman** [comment]
Can you provide more details - which component, and the scenario you'd want to prevent close?

**Comment by hernandp-nimble** [comment]
Sorry for the lack of information, I was talking about the dialog. Also nested dialogs render inside each other and cannot be set to absolute if you have relative containers on top. I saw in other libraries they use Portals to manage this better, don't know if that can be a solution

**Comment by CaptainCodeman** [comment]
And what is the situation where the user wants to close a dialog, but the system should get to say "nuhuh"? IMO it should always be equivalent to a 'cancel' action.

I'm not a fan of nested dialogs, I think the UX should always be re-thought at that point.

**Comment by CaptainCodeman** [comment]
I see, so you want to protect against _accidental_ closure from them clicking anything but the `close` button.

**Comment by zinkkrysty** [comment]
> I see, so you want to protect against _accidental_ closure from them clicking anything but the `close` button.

Yes, that's correct.
